version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Git and Maven softwares
      - yum install git -y
      - yum install maven -y
  build:
    commands:
      - echo Maven Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo checking build files
      - ls -l target
