version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Git and Maven softwares
      - yum install git -y
      - yum install maven -y
      - cp settings.xml /root/.m2
      - yum install docker* -y

  build:
    commands:
      - echo Maven Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo checking build files
      - ls -l target
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335590865.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t batch106 .
      - docker tag batch106:latest 730335590865.dkr.ecr.us-east-1.amazonaws.com/batch106:latest
      - docker push 730335590865.dkr.ecr.us-east-1.amazonaws.com/batch106:latest
