version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Git and Maven softwares
      - docker --version
  build:
    commands:
      - echo docker images upload
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 156041422561.dkr.ecr.ap-south-1.amazonaws.com
      - docker build -t testecrrpo .
      - docker images
      - docker tag testecrrpo:latest 156041422561.dkr.ecr.ap-south-1.amazonaws.com/testecrrpo:latest
