version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Git and Maven softwares
      - yum install git -y
      - yum install maven -y
      - cp settings.xml /root/.m2

  build:
    commands:
      - echo Maven Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - echo checking build files
      - ls -l target
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain prasad --domain-owner 730335590865 --region us-east-1 --query authorizationToken --output text`
      - mvn deploy
