version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing Git and Maven softwares
      - yum install git -y
      - cp settings.xml /root/.m2
      - docker --version
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain test-artifact --domain-owner 156041422561 --region ap-south-1 --query authorizationToken --output text`

  build:
    commands:
      - echo Maven Build started on `date`
      - mvn clean install
      - ls -l target
      - mvn deploy
